#!/usr/bin/env ruby

require 'time'
require 'uri'
require 'bundler/setup'
Bundler.require(:default)

$api_key = '0cb0ee5c77250abd8700604ac2b017d9830971bcb316088f8'

project_root = File.dirname(File.absolute_path(__FILE__))
Dir.glob(project_root + '/functions/*', &method(:require))

args = ARGV
if args.empty?
  word_of_the_day()
else
  case args[0]
  when 'def'
    res = definition(args[1])
    output(res)
  when 'syn'
    res = synonym(args[1])
    output(res)
  when 'ant'
    res = antonym(args[1])
    output(res)
  when 'ex'
    res = example(args[1])
    output(res)
  when 'play'
    game()
  when 'dict'
    detail(args[1])
  else
    detail(args[0])
  end
end
